// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqwowuzzzovettfkhwwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxd293dXp6em92ZXR0Zmtod3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTUxNDMsImV4cCI6MjA2OTk3MTE0M30.oJo7M7Nd7Mjh6kg1BTzRQ9PE7zG77jvS170PnViX1mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});